### ISSUE TITLE
[BUG] Appling HMR and higher timestep results in simulation instability

### ISSUE THREAD

**Issue by akalpokas** [OpenBioSim/somd2#13]
# Describe the bug

Applying HMR and increasing the timestep to `4fs` seems to crash SOMD2 simulations with TYK2 dataset when using the most recent version of SOMD2 (`0.1.dev220+geb89275.d20231205`). The particular example runs fine at `2fs` timestep with/without HMR applied, but the dynamics crash immediately once a higher timestep is used. I was able to run these simulations with HMR and `4fs` timestep using a previous version of SOMD2 (`0.1.dev169+ga642d47`).

Interestingly, I can use the [sire faster FEP script](https://sire.openbiosim.org/tutorial/part06/06_faster_fep.html#complete-example-script) to run same the perturbation and the input file with HMR applied at `4fs` timestep in the same conda envrionment that this version of SOMD2 is installed, which makes me believe that there might be an issue with the way SOMD2 is either applying HMR or passing the system to sire with HMR applied to do the dynamics?

I tried to debug by printing out the masses before and after HMR is applied for the perturbable molecule, and I get the same masses between the sire script and SOMD2, so my guess it's the latter, although there could be something else going on that I haven't considered entirely (like the recent updates to the constraints code).

# To reproduce

### To test SOMD2 crashing

Run provided input file with:
```bash
somd2 lig_ejm31-lig_ejm42.bss --timestep 4fs --h-mass-factor 1.5 --cutoff-type rf --num-lambda 21 --log-level debug --runtime 500ps --equilibration-time 2ps --energy-frequency 0.1ps --no-save-trajectories
```
Which should crash immediately. Now reduce the timestep to `2fs`, and this runs fine.

### To show sire can run the system at `4fs` timestep with HMR:

Run the following code, which is adapted from [sire faster FEP script](https://sire.openbiosim.org/tutorial/part06/06_faster_fep.html#complete-example-script):

```python
import sire as sr

mols = sr.load(f"lig_ejm31-lig_ejm42.bss")

for mol in mols.molecules("molecule property is_perturbable"):
    mol = mol.perturbation().link_to_reference().commit()
    mol = sr.morph.repartition_hydrogen_masses(mol, mass_factor=1.5)
    mols.update(mol)

mols = mols.minimisation().run().commit()

timestep = "4fs"
energy_frequency = "0.1ps"

constraint = "h-bonds"
perturbable_constraint = None

equil_time = "2ps"
run_time = "500ps"

lambda_values = [x / 100.0 for x in range(0, 101, 5)]

print("\nWater leg")

for i, lambda_value in enumerate(lambda_values):
    print(f"Simulating lambda={lambda_value:.2f}")
    # minimise the system at this lambda value
    min_mols = mols.minimisation(lambda_value=lambda_value,
                                 constraint=constraint,
                                 perturbable_constraint="none").run().commit()

    # create a dynamics object for the system
    d = min_mols.dynamics(
        timestep=timestep,
        temperature="25oC",
        lambda_value=lambda_value,
        constraint=constraint,
        perturbable_constraint=perturbable_constraint,
        cutoff_type="RF"
    )

    # generate random velocities
    d.randomise_velocities()

    # equilibrate, not saving anything
    d.run(equil_time, save_frequency=0)
    print("Equilibration complete")
    print(d)

    # get the values of lambda for neighbouring windows
    lambda_windows = lambda_values[
        max(i - 1, 0) : min(len(lambda_values), i + 2)
    ]

    # run the dynamics, saving the energy every 0.1 ps
    d.run(
        run_time,
        energy_frequency=energy_frequency,
        frame_frequency=0,
        lambda_windows=lambda_windows,
    )
    print("Dynamics complete")
    print(d)

    # stream the EnergyTrajectory to a sire save stream object
    sr.stream.save(
        d.commit().energy_trajectory(), f"energy_water_{lambda_value:.2f}.s3"
    )
```

# Input files

[inputs.tar.gz](https://github.com/OpenBioSim/somd2/files/13565813/inputs.tar.gz)

# Environment information:

SOMD2 version: `0.1.dev220+geb89275.d20231205`
BioSimSpace version: `2023.5.0.dev` 
Sire version: `2023.5.0.dev` ([106d783](https://github.com/OpenBioSim/sire/commit/106d78388eaf929a3c0ac3a95f5cf71ed01d4eba)) as far as I can tell

**Comment by lohedges** [comment]
I think this is probably related to the feature/fix branch that Matthew is working on to make sure that HMR is applied correctly when equilibration is used. Are things stable if you perform no equilibration?

**Comment by lohedges** [comment]
Also, as you have found, Sire and SOMD2 use identical HMR code internally.

**Comment by chryswoods** [comment]
I think this is related to what I've just found as I am running more tests for the `2023.5.0` release.

The fix just merged into `devel` included a change to the LJ parameters for exceptions such that we replace anything with `sig=0,eps=X` with `sig=1,eps=0`. This is because using `sig=0` leads to numerical instabilities in OpenMM.

However, this seems to lead to numerical instabilities when running free energy simulations. Changing the code so that we use `sig=1e-9,eps=0` fixes this problem for me. I've pushed this change to `feature_optimise_lever` and will talk to Exscientia to see if they are ok having that as the fix.

(the [commit here](https://github.com/OpenBioSim/sire/commit/07e8dea23bba6e86448973c97971e0d57b3d6d67) is the fix)

**Comment by akalpokas** [comment]
> I think this is probably related to the feature/fix branch that Matthew is working on to make sure that HMR is applied correctly when equilibration is used. Are things stable if you perform no equilibration?

Sorry I forgot to mention that I tried it with/without equilibration and with/without minimisation and it was still crashing consistently above `2fs` timestep. 

I will try the latest version of `feature_optimise_lever` and see whether that fixes the issue.

**Comment by akalpokas** [comment]
I can confirm that this still crashes with SOMD2 built with latest version of sire's `feature_optimise_lever` branch.

**Comment by mb2055** [comment]
I'm seeing the same behaviour. It seems to be the  `constraint` and `perturbable_constraint` flags. SOMD2 uses `"none"` for both of these arguments when equilibrating, whereas your script uses `"h-bonds"` and `None` (note that `None` and `"none"` have different behaviours) respectively. I'll do some testing and see which default values work best.

**Comment by jmichel80** [comment]
what is constrained when ''none'' is specified ? For instance when simulating a rigid water model it could be argued that it is incorrect to not use any constraints on the water molecules.

**Comment by lohedges** [comment]
I'm not actually sure how water molecules are treated in the Sire to OpenMM conversion. In the OpenMM Python API there is a `rigidWater` keyword that is (I think) independent from the constraint on the other molecules.

**Comment by lohedges** [comment]
> what is constrained when ''none'' is specified 

This is explicitly no constraints. Using `None` allows Sire to choose an appropriate constraint based on the time step. As mentioned above, I'm not sure what `"none"` means for water molecules. Will check the code to see if they are handled separately.

**Comment by chryswoods** [comment]
Water molecules are treated like all other molecules, e.g. if you specify h-bonds then the bonds involving hydrogen are constrained.

The 'None' means to let sire decide automatically what is best based on the timestep. Using "none" (the string) says that you don't want any constraints all.

For perturbable_constraint, using None will set it to use whatever is used for all other molecules. Setting it to "none" will say not to use any constraints for perturbable molecules (needed for equilibration or minimisation at least, or you won't let perturbable bonds change length).

The sire tutorial does go through all this, and the example in that tutorial is constructed in that tutorial by exploring what schemes worked well for ethane to methanol.

**Comment by chryswoods** [comment]
The best default options for somd2 should be None (decide based on the timestep) and "none" (don't constrain perturbable molecules during minimisation or equilibration)

**Comment by mb2055** [comment]
Looking a bit deeper, it seems that the issue in `SOMD2` is with the `perturbable_constraint` argument within the production run, it should work if this argument is set explicitly to `h_bonds`. Currently `SOMD2` sets this to `"none"` in the production step by default, this needs to be changed to something more sensible.
@chryswoods it seems that the `"auto"` argument has distinctly different behaviour to `None` for `perturbable_constraint`, is this intended behaviour? For example, the system above will crash with `"auto"` but not with `None` (I was hoping to change the behaviour of `SOMD2` to use `"auto"` by default since we can't really use `None` with the CLI when `"none"` is also an option).

**Comment by mb2055** [comment]
Ok, that makes sense.
I'll try to come up with a way to expose the two options to the user in a clear way - I suppose we could use `None` when the user doesn't set a value for `perturbable-constraint` in the CLI. Alternatively we could add an extra option along the lines of `match` so that its clear that it will use the same option for both `constraint` and `perturbable_constraint` that just sets it to `None` in the background.

**Comment by lohedges** [comment]
I think the confusion is this:

```python
In [1]: import sire as sr

In [2]: mols = sr.load_test_files("merged_molecule.s3")


In [3]: for mol in mols.molecules("molecule property is_perturbable"):
   ...:     mols.update(mol.perturbation().link_to_reference().commit())
   ...:

In [4]: d = mols.dynamics(constraint="h-bonds", perturbable_constraint=None)

In [5]: d.perturbable_constraint()
Out[5]: 'none'

In [6]: d = mols.dynamics(constraint="h-bonds", perturbable_constraint="h-bonds")

In [7]: d.perturbable_constraint()
Out[7]: 'h_bonds'

In [8]: d = mols.dynamics(constraint="h-bonds", perturbable_constraint="auto")

In [9]: d.perturbable_constraint()
Out[9]: 'none'

In [10]: d = mols.dynamics(constraint="h-bonds", perturbable_constraint="none")

In [11]: d.perturbable_constraint()
Out[11]: 'none'
```

In this case, if perturbable constraint is set to `None`, i.e. `NoneType`,  then the resulting perturbable constraint for the dynamics object is `'none'` (`str` type). The same thing is true regardless of the time step. Here it looks like `None` is being converted to `auto`, which is then choosing `'none'`. In all cases, the resulting perturbable constraint (reported by the function) does _not_ match the non-perturbable constraint.

This is why we had assumed that `None` was just being converted to `"auto"`. However, if I print the map at the point at which the Sire to OpenMM conversion is happening, then I see that `perturbable_constraint` _is_ absent from the map, i.e. it is unset. Looking at the `SOMMContext` code I see:

```python
    def get_perturbable_constraint(self):
        """
        Return the perturbable constraint applied to the system
        """
        if self._map.specified("perturbable_constraint"):
            return self._map["perturbable_constraint"].source()
        else:
            return "none"
```

This means that `'none"` is being returned whenever `perturbable_constraint` is absent from the map, i.e. what is being reported isn't actually what was set. For clarity, here's the C++ code that shows that the perturbable constraint _is_ set to the regular constraint when it is unset, i.e. the behaviour that is described in @chryswoods' comment above:

```cpp
    if (map.specified("perturbable_constraint"))
    {
        const auto c = map["perturbable_constraint"].source().toLower().simplified();


        if (c == "none")
        {
            perturbable_constraint_type = CONSTRAIN_NONE;
        }
        else if (c == "h-bonds" or c == "h_bonds")
        {
            perturbable_constraint_type = CONSTRAIN_HBONDS;
        }
        else if (c == "bonds")
        {
            perturbable_constraint_type = CONSTRAIN_BONDS;
        }
        else if (c == "h-bonds-h-angles" or c == "h_bonds_h_angles")
        {
            perturbable_constraint_type = CONSTRAIN_HBONDS | CONSTRAIN_HANGLES;
        }
        else if (c == "bonds-h-angles" or c == "bonds_h_angles")
        {
            perturbable_constraint_type = CONSTRAIN_BONDS | CONSTRAIN_HANGLES;
        }
        else
        {
            throw SireError::invalid_key(QObject::tr(
                                             "Unrecognised perturbable constraint type '%1'. Valid values are "
                                             "'none', 'h-bonds', 'bonds', 'h-bonds-h-angles' or "
                                             "'bonds-h-angles',")
                                             .arg(c),
                                         CODELOC);
        }
    }
    else
    {
        perturbable_constraint_type = constraint_type;
    }
```

I think the Python code should just set the map value of `perturbable_constraint` to the value of `constraint` when `perturbable_constraint=None`. This will avoid any confusion, since `d.perturbable_constraint()` will report the correct value. We can also document this behaviour to make the intent clear.

**Comment by chryswoods** [comment]
Yes - you are right why we can't make the decision to map `perturbable_constraint` to `constraint` at the top level. The design has this decision made at the bottom. We have to leave `perturbable_constraint` equal to `None` whenever the user has not expressed a preference (that is what a flag of `None` normally means - it shows that the user has not expressed a preference).

The two choices I see are;

1. somd2 accepts the way sire sets these flags, and so somd2 does not set a flag unless the user has explicitly set that (i.e. if the user does not supply `perturbable_constraint`, then make sure that `perturbable_constraint` is left as `None`). This retains the bottom-up approach to these flags that sire needs to support both API access and `map` access to these flags.

2. somd2 creates its own set of options and manages them from the top-down. So somd2 includes options and does the full logic of deciding how `constraint` and `perturbable_constraint` are to be set based on the somd2-specific options that are supplied by the user.
